---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.6.redhat-00004
    app.quarkus.io/commit-id: 77424a63f4b7aad738ac108601888379356279a3
    app.quarkus.io/vcs-uri: https://github.com/batzionb/catalog-workflow.git
    app.quarkus.io/build-timestamp: 2025-06-24 - 14:16:09 +0000
  labels:
    app.kubernetes.io/name: serverless-workflow-order
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: serverless-workflow-order
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: serverless-workflow-order
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: view-jobs
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: serverless-workflow-order
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: serverless-workflow-order-view-jobs
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-jobs
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: serverless-workflow-order
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.6.redhat-00004
    app.quarkus.io/commit-id: 77424a63f4b7aad738ac108601888379356279a3
    app.quarkus.io/vcs-uri: https://github.com/batzionb/catalog-workflow.git
    app.quarkus.io/build-timestamp: 2025-06-24 - 14:16:09 +0000
  labels:
    app.kubernetes.io/name: serverless-workflow-order
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: serverless-workflow-order
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: serverless-workflow-order
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.6.redhat-00004
    app.quarkus.io/commit-id: 77424a63f4b7aad738ac108601888379356279a3
    app.quarkus.io/vcs-uri: https://github.com/batzionb/catalog-workflow.git
    app.quarkus.io/build-timestamp: 2025-06-24 - 14:16:09 +0000
  labels:
    app.kubernetes.io/name: serverless-workflow-order
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: serverless-workflow-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: serverless-workflow-order
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.8.6.redhat-00004
        app.quarkus.io/commit-id: 77424a63f4b7aad738ac108601888379356279a3
        app.quarkus.io/vcs-uri: https://github.com/batzionb/catalog-workflow.git
        app.quarkus.io/build-timestamp: 2025-06-24 - 14:16:09 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: serverless-workflow-order
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_FLYWAY_ENABLED
              value: "false"
          image: docker.io/org.kie.kogito/serverless-workflow-order:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: serverless-workflow-order
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      initContainers:
        - args:
            - job
            - serverless-workflow-order-flyway-init
          image: groundnuty/k8s-wait-for:no-root-v1.7
          imagePullPolicy: IfNotPresent
          name: wait-for-flyway
      serviceAccountName: serverless-workflow-order
---
apiVersion: batch/v1
kind: Job
metadata:
  name: serverless-workflow-order-flyway-init
spec:
  completionMode: NonIndexed
  template:
    metadata: {}
    spec:
      containers:
        - env:
            - name: QUARKUS_INIT_AND_EXIT
              value: "true"
            - name: QUARKUS_FLYWAY_ENABLED
              value: "true"
          image: docker.io/org.kie.kogito/serverless-workflow-order:1.0.0-SNAPSHOT
          name: serverless-workflow-order-flyway-init
      restartPolicy: OnFailure
      serviceAccountName: serverless-workflow-order
